# Hospitality-Revenue-Analysis-Dashboard
##   Project Objective 
To design an interactive Power BI dashboard that enables hotel management to monitor and analyze key revenue metrics, occupancy rates, and operational KPIs across multiple locations. The goal is to support data-driven decision-making, optimize pricing strategies, and improve overall business performance.
## Technologies Used 
Power BI – For dashboard design and data visualization

Power Query – For transforming and cleaning raw data

DAX (Data Analysis Expressions) – For creating custom measures and KPIs

Excel – As the data source for bookings and revenue metrics

## Data Cleaning and Tranformation
Used Power Query Editor for cleaning and shaping data, including:

Removed unnecessary columns and blanks

Fixed data types and date formats

Split columns and created conditional fields

Merged tables and applied filters to handle outliers

## Dashboard Preview 
This Power BI dashboard provides key insights into hospitality performance across cities and properties.

Highlights:

Top KPIs:

Revenue: ₹1.69B | RevPar: ₹7,337 | DSRN: 2,528

Occupancy: 57.79% | ADR: ₹12.70K | Realisation %: 70.14%


Visuals:

Donut chart: Revenue split by category

Line chart: Trends in key metrics (RevPar, ADR, Occupancy)

Bar chart: Realisation % & ADR by booking platform

Table: City/property-wise performance breakdown


Filters:

Week | City | Room Type
## Key Insights
High Revenue Performance:
Total revenue stands at ₹1.69B with strong RevPar of ₹7,337, indicating effective room yield.

Occupancy vs Realisation:
Occupancy is moderate at 57.79%, but Realisation % is relatively high at 70.14%, suggesting effective pricing strategies.

Platform Contribution:
MakeMyTrip and Goibibo show higher ADR and Realisation %, indicating better performance through these platforms.

Category Revenue Split:
A large share of revenue comes from Leisure bookings, followed by Business and Group categories.

Top-Performing Cities:
Cities like Delhi and Mumbai lead in revenue and occupancy, while others show potential for improvement.

Consistent Trends:
Weekly trends show stable movement in key metrics, with no major dips or spikes, reflecting operational consistency.


![Screenshot 2025-04-30 013422](https://github.com/user-attachments/assets/7e95906a-e0bd-44de-b1b1-c377890fbb56)


